application: treeurl
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style

- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest
